name: 4D BIM User Group
favicon: null
layout_spectrum: 0.9042770373634994
typography_spectrum: 0.7129729161970317
title: 4D BIM User Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2231'
    - '#e7e7e7'
    - '#6368a3'
    - '#333a68'
    - '#a9a8a3'
  brandStrength: 0.1875
  lightness: 0.5344899918418378
  saturation: 0.7246213131584227
  rhythmicContrast: 0.75
purpose: []
